feat(mapper)!: I have added new features to the commit log mapper
This is more information about the commit

Jin you should look at this @jin

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -1,3 +1,10 @@
-#!/usr/bin/env ruby
+#!/usr/bin/env bash
 
-# frozen_string_literal: true
+if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?!?: .{1,}$"; then
+    echo "Aborting commit. Please follow conventional commit message guidelines" >&2
+    exit 1
+fi
+if ! head -1 "$1" | grep -qE "^.{1,200}$"; then
+    echo "Aborting commit. Your commit message is too long." >&2
+    exit 1
+fi
